use_frameworks!

target 'FormatTextField_Example' do
  pod 'FormatTextField', :path => '../'

  target 'FormatTextField_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
